### ISSUE TITLE
Provide possibility to runt Groovy Script without substring 'groovyconsole' in file path

### ISSUE THREAD

**Issue by sromazanov** [DenisKusakin/aem-groovyconsole-idea-plugin#12]
Plugin allows to run Groovy script only if file path has "groovyconsole" substring. Could you please remove this restriction. Or as alternative substring pattern may be introduced in preferences.

**Comment by DenisKusakin** [comment]
Hi @sromazanov !
Thanks for the report, the issue will be fixed.

**Comment by sromazanov** [comment]
Thank you @DenisKusakin for this feature. it's really good improvement!
