### ISSUE TITLE
AEM imports not working

### ISSUE THREAD

**Issue by tadijam64** [DenisKusakin/aem-groovyconsole-idea-plugin#18]
I have a problem with first usage of this plugin. 
I set server in settings and installed plugin. After that marked directory with groovy files as Groovy directory. I am using IntelliJ 2018.3.4v and JRE 1.8.0.

The problems occur when I try to run the program that is **successfully run in browser AEM groovy console** (on server).
AEM imports are not recognized and the program can not be run due to following exception:

**org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:**
`/.../.../engines/core/src/main/java/we/retail/core/groovyScripts/assetUpdate.groovy: 4: unable to resolve class org.apache.sling.api.resource.ValueMap
 @ line 4, column 1.
   import org.apache.sling.api.resource.ValueMap
   ^

/.../.../engines/core/src/main/java/we/retail/core/groovyScripts/assetUpdate.groovy: 3: unable to resolve class org.apache.sling.api.resource.Resource
 @ line 3, column 1.
   import org.apache.sling.api.resource.Resource
   ^

/.../.../engines/core/src/main/java/we/retail/core/groovyScripts/assetUpdate.groovy: 2: unable to resolve class org.apache.sling.api.resource.ModifiableValueMap
 @ line 2, column 1.
   import org.apache.sling.api.resource.ModifiableValueMap
   ^

3 errors

Process finished with exit code 1`

**Comment by DenisKusakin** [comment]
Hi @tadijam64 
The plugin does not perform any compilation, so such error message looks a bit odd for me
Could you please make a screenshot of what you see in your IDE?

**Comment by tadijam64** [comment]
<img width="1633" alt="Screenshot 2019-09-26 at 22 00 30" src="https://user-images.githubusercontent.com/21061194/65720947-531cc500-e0a9-11e9-90da-85a9570ad005.png">

**Comment by DenisKusakin** [comment]
Looks like you are trying to execute groovy via default IntelliJ groovy console
Try to close run tab with wrong execution (red square) and then execute the script again using CTRL + Enter or by clicking run icon next to your AEM server name (yellow square)
![65720947-531cc500-e0a9-11e9-90da-85a9570ad005](https://user-images.githubusercontent.com/11842086/65748921-ade80800-e10d-11e9-9183-81c21ed6470d.png)

**Comment by tadijam64** [comment]
Thank you. I thought it should be run with intelliJ groovy console. It would be good to mention this somewhere in README file. If it is already somewhere written, I apologise for confusion :)

**Comment by DenisKusakin** [comment]
Thank you for your feedback, I agree that it might confuse
I will mention it somewhere
